### ISSUE TITLE
Add New Rent A Car Design

### ISSUE THREAD

**Issue by MayomiSGunawardana** [sublimemahesh/hurryuptaxi.lk#111]
Design **tab**

**Comment by sublimemahesh** [comment]
- Change "Name" to "Title or Vehicle"
- Change "Conatc Name" and place holder "Enter Conatc Name" to "Contact Name" ane Enter Contact Name"

**Comment by sublimemahesh** [comment]
There are 3 tabs

1. Vehicle Owner Details
2. Vehicle Details
3. Prices

**1. Vehicle Owner Details**
- Contact Name 
- Phone Number 
- Email 
- District 
- City 
- Address  

**2. Vehicle Details**
- Title or Vehicle 
- Vehicle Type 
- Request Type 
- Fuel Type
- Vehicle Number 
- No Of Passengers 
- No Of Baggage 
- No Of Doors 
- Air Conditioned 

**3. Prices**
Self Drive
Tours / Chauffeur Driven
Airport / City Transfers
Weddings & Events
